-- Arquivo referente a criação da tabela ESTADO

CREATE DATABASE IF NOT EXISTS iCasamento;

USE iCasamento;

CREATE TABLE IF NOT EXISTS estado (
    ESTA_CD_ESTADO INT PRIMARY KEY,
    ESTA_NM_ESTADO VARCHAR(255),
    ESTA_SG_SIGLA VARCHAR(2)
);

CREATE INDEX ESTA_CD_ESTADO ON estado (ESTA_CD_ESTADO);
CREATE INDEX ESTA_NM_ESTADO ON estado (ESTA_NM_ESTADO);
CREATE INDEX ESTA_SG_SIGLA ON estado (ESTA_SG_SIGLA);