-- Arquivo referente a criação da tabela TIPO_PRESENTE

CREATE DATABASE IF NOT EXISTS iCasamento;

USE iCasamento;

CREATE TABLE IF NOT EXISTS tipo_presente (
    TIPR_CD_TIPO_PRESENTE INT PRIMARY KEY,
    TIPR_NM_TIPO_PRESENTE VARCHAR(255),
);

CREATE INDEX TIPR_CD_TIPO_PRESENTE ON cidade (TIPR_CD_TIPO_PRESENTE);
CREATE INDEX TIPR_NM_TIPO_PRESENTE ON cidade (TIPR_NM_TIPO_PRESENTE);
