-- Arquivo referente a criação da tabela CONVIDADO

CREATE DATABASE IF NOT EXISTS iCasamento;

USE iCasamento;

CREATE TABLE IF NOT EXISTS convidado (
    CONV_CD_CONVIDADO INT PRIMARY KEY,
    CONV_NM_CONVIDADO VARCHAR(255),
    CONV_NR_TELEFONE VARCHAR(11),
    CONV_NM_EMAIL VARCHAR(255),
    CONV_TX_CPF VARCHAR(11),
    CONV_CD_SENHA VARCHAR(255)
);

CREATE INDEX CONV_CD_CONVIDADO ON convidado (CONV_CD_CONVIDADO);
CREATE INDEX CONV_NM_CONVIDADO ON convidado (CONV_NM_CONVIDADO);
CREATE INDEX CONV_NR_TELEFONE ON convidado (CONV_NR_TELEFONE);
CREATE INDEX CONV_NM_EMAIL ON convidado (CONV_NM_EMAIL);
CREATE INDEX CONV_TX_CPF ON convidado (CONV_TX_CPF);
CREATE INDEX CONV_CD_SENHA ON convidado (CONV_CD_SENHA);