-- Arquivo referente a criação da tabela LOCAL_CASAMENTO

CREATE DATABASE IF NOT EXISTS iCasamento;

USE iCasamento;

CREATE TABLE IF NOT EXISTS local_casamento (
    LOCA_CD_LOCAL_CASAMENTO INT PRIMARY KEY,
    LOCA_NM_LOCAL_CASAMENTO VARCHAR(255),
    LOCA_QTD_CONVIDADOS INT,
    -- Chaves estrangeiras referentes as tabelas CIDADE e ESTADO
    FOREIGN KEY (CIDA_CD_CIDADE) REFERENCES CIDADE(CIDA_CD_CIDADE),
    FOREIGN KEY (ESTA_CD_ESTADO) REFERENCES ESTADO(ESTA_CD_ESTADO)
);

CREATE INDEX LOCA_CD_LOCAL_CASAMENTO ON local_casamento (LOCA_CD_LOCAL_CASAMENTO);
CREATE INDEX LOCA_NM_LOCAL_CASAMENTO ON local_casamento (LOCA_NM_LOCAL_CASAMENTO);
CREATE INDEX LOCA_QTD_CONVIDADOS ON local_casamento (LOCA_QTD_CONVIDADOS);