-- Arquivo referente a criação da tabela CIDADE

CREATE DATABASE IF NOT EXISTS iCasamento;

USE iCasamento;

CREATE TABLE IF NOT EXISTS cidade (
    CIDA_CD_CIDADE INT PRIMARY KEY,
    CIDA_NM_CIDADE VARCHAR(255),
    CIDA_SG_SIGLA_ESTADO VARCHAR(2)
);

CREATE INDEX CIDA_CD_CIDADE ON cidade (CIDA_CD_CIDADE);
CREATE INDEX CIDA_NM_CIDADE ON cidade (CIDA_NM_CIDADE);
CREATE INDEX CIDA_SG_SIGLA_ESTADO ON cidade (CIDA_SG_SIGLA_ESTADO);